#!/usr/bin/env bash
# A
git submodule foreach --recursive mkdir -p .skogai/git
git submodule foreach --recursive cp /home/skogix/skogai/.skogai/git/* ./.skogai/git/
git submodule foreach --recursive git add .
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
git submodule foreach --recursive git add ./.skogai/git
git submodule foreach --recursive git commit -m "Add/Update .skogai/git" --no-verify
# git submodule foreach --recursive ./.skogai/b
